// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXa6uzgGkHstPj_BuodUCisZBAYqf_aM',
    appId: '1:714328318577:android:9faf8bc863348b196db1d0',
    messagingSenderId: '714328318577',
    projectId: 'spending-docs',
    storageBucket: 'spending-docs.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbIyNRW_I2NjXEkyYOB04veZW1QHKlmc',
    appId: '1:714328318577:ios:a9d9addb878bb84d6db1d0',
    messagingSenderId: '714328318577',
    projectId: 'spending-docs',
    storageBucket: 'spending-docs.firebasestorage.app',
    iosBundleId: 'com.example.spendingDocs',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbIyNRW_I2NjXEkyYOB04veZW1QHKlmc',
    appId: '1:714328318577:ios:a9d9addb878bb84d6db1d0',
    messagingSenderId: '714328318577',
    projectId: 'spending-docs',
    storageBucket: 'spending-docs.firebasestorage.app',
    iosBundleId: 'com.example.spendingDocs',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7roziV1mvfrw2PL5wkRawnTlPcBmdKJw',
    appId: '1:714328318577:web:adfe6cfa6d021e516db1d0',
    messagingSenderId: '714328318577',
    projectId: 'spending-docs',
    authDomain: 'spending-docs.firebaseapp.com',
    storageBucket: 'spending-docs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7roziV1mvfrw2PL5wkRawnTlPcBmdKJw',
    appId: '1:714328318577:web:f78a0674865ea9c86db1d0',
    messagingSenderId: '714328318577',
    projectId: 'spending-docs',
    authDomain: 'spending-docs.firebaseapp.com',
    storageBucket: 'spending-docs.firebasestorage.app',
  );
}
